---
title: "Pronomi"
---

# Pronom toniques

Used to reinforce idea. Moi, je préfère Venice

| Moi       |
|-----------|
| Toi       |
| Lui/Elle  |
| Nous      |
| Vous      |
| Eux/Elles |

# pronom en

Replace a noun preceded by:

-   articolo indefinito. Il a une voiture → il en a une
-   articolo partitivo (du, de la, etc.). Il vend du vin → il en vend
-   a quantifier (un kilo, assez de, beaucoup...). If the quantity is defined, we add it at the end of the sentence: il achète un kilo de pommes → il en achète un kilo.

To make the negative: il ne boit pas de vin → il n'en boit pas

# Pronom y

Replace a situation or a destination:

-   Elle est au bureau? Oui, elle y est
-   Elle va à la réunion? Oui, elle y va

# Pronome indefinito

-   **Certain** sont riches, **d'autres** sont pauvres
-   Chacun, chacune → Il y a quatre médecins, chacun a sa spécialité
-   Tous, toutes → Ile viennent tous (Quando tous è pronome, si pronuncia la s finale)
-   Tout = everything → Tout est prêt

# Prenoms COD

-   Je connais (CHI?) David
-   J'appelle (CHI?) David

Il COD rimpiazza un nome che nell frase risponde alla domanda chi/che cose (i.e., un complement oggetto, Complement Object Direct in francese):

| Le                               | La                               | Les                                        |
|----------------------------------|----------------------------------|--------------------------------------------|
| Je connais David. Je le connais. | Je connais Alice. Je la connais. | Je connais David et Alice. Je les connais. |
| J'appelle David. Je l'appelle.   | J'appelle Alice. Je l'appelle.   | J'appelle David et Alice. Je les appelle.  |

Same idea to use m(e), t(e), vous.

# Prenoms COI

Rimpiazzano un complemento indiretto:

-   J'écris (A CHI?) à Mario

| Me                                |
|-----------------------------------|
| Te                                |
| Lui (sia maschile che femminile)  |
| Nous                              |
| Vous                              |
| Leur (sia maschile che femminile) |

## Placement of pronouns COI/COD, verbs, ne/pas

-   Simple verb: COI/COD prima del verbo
    -   Je lui mange
    -   Je ne lui mange pas
-   Passé composé: COI/COD prima dell'ausiliare, pas tra ausiliare e verbo
    -   Je lui ai dit la vérité
    -   Je ne lui ai pas dit la vérité
-   Semi-ausiliari (volere, potere, etc.): COI/COD tra semi-ausiliare e verbo. Pas tra verbo e COI/COD
    -   Je veux lui dire la vérité
    -   Je ne veux pas lui dire la vérité

**SOGGETTO NE** SEMI-AUSILIARE PAS COI **VERBO**

**SOGGETTO NE** COI AUSILIARE PAS **VERBO**
