---
title: "Questions"
---

# Styles

- When there is question word (qui/quoi/quand/comment/etc.), this world always must go at the beginning of the question in the style courant e style soutenu
- style **familier**: come la frase affermativa, cambia solo l’intonazione
- style **courant**: **Est-ce que** vous travaillez ici?
- style **soutenu**: inversione verbo-soggetto

# Qui, Quoi, Que

- Qui for a person
- Quoi/que for an object
- Qui e quoi possono essere preceduti da una preposizione:
  - Avec qui est-ce que vous travaillez?
  - À quoi est-ce que tu penses?
  
- Qui est-ce?
  - C’est Pierre
  - C’est **un** avocat
  - Il est ~~un~~ avocat
    
- Qu’est que c’est?
  - C’est un stylo
  - Ce sont des stylos
    
- Qui/Qu’est-ce qui/que […]?
    - Question on a person
        - **Qui** est-ce **qui** travaille ici? [In questo caso  sostituisce il soggetto]
        - **Qui** est-ce **que** tu attends? [In questo caso  sostituisce il COD]
    - Question on a thing
        - **Qu**’est-ce **qui** brille dans le ciel? [**qui** sostituisce il soggetto]
        - **Qu**’est-ce **que** tu vois? [**que** sostituisce COD]
  
- Courant:
  - Qui est-ce que vous avez invité?
  - C’est qui?
  - Qu’est-ce qu’il fait?
- Soutenu
  - Qui avez-vous invité?
  - Qui est-ce?
  - Que fait-il?
  

# Quel/Quelle
    
- Può essere preceduto da preposizione:
  - Dans quel pays habitez-vous?
    
- Courant
  - Quelles langues est-ce que vous  parlez?
- Soutenu
  - Quelles langues parlez-vous?

# Où/quand/pourquoi/comment/combien (circumstances)
- Familer
  - Tu gagnes combien?
- Courant
  - Combien est-ce que tu gagnes?
- Soutenu
  - Combien gegnes-tu?

# lequel/lesquels/laquelle/lesquelle (choice)

