---
title: "Presente indicativo"
---

## Primo gruppo (-er)

| Je parl**e**     |
|------------------|
| Tu parl**es**    |
| Il parl**e**     |
| Nous parl**ons** |
| Vous parl**ez**  |
| Ils parl**ent**  |


**Eccezioni**

-   Se la radice finisce con una -e prima della consonante: la vocale che precede il suffisso prende un accento grave. Préf**é**rer, ach**e**ter

| Je préfère     | J'achète      |
|----------------|---------------|
| Tu préfères    | Tu achètes    |
| Il préfère     | Il achète     |
| Nous préférons | Nous achetons |
| Vous préférez  | Vous achetez  |
| Ils préfèrent  | Ils achètent  |

-   Si raddoppia la consonante in:

| Je jet**t**e  | J'appel**l**e   |
|---------------|-----------------|
| Tu jet**t**es | Tu appel**l**es |
| Il jet**t**e  | Il appel**l**e  |
| Nous jeton    | Nous appelons   |
| Vous jetez    | Vous appelez    |
| Ils jettent   | Ils appellent   |

-   Verbi in -ayer, -oyer, -uyer. Solo per la prima persona singolare la -y diventa -i: - Je pa**i**e/pa**y**e (entrambi accettabili) - Je envo**i**e

-   Verbi on -ger or -cer (i.e., mager o commencer). Nella 2 persona plurale per mantenere la pronuncia si cambia in:

| Nous mangeons   | Aggiungere una -e dopo la -g |
|-----------------|------------------------------|
| Nous commençons | La -c diventa -ç             |


## Secondo gruppo (-ir)

-   Pluriel en -iss

| je grossi**s**            |                       |
|---------------------------|-----------------------|
| tu grossi**s**            |                       |
| il/elle/on grossi**t**    |                       |
| nous gross**issons**      | add -ss before suffix |
| vous gross**issez**       | add -ss before suffix |
| ils/elles gross**issent** | add -ss before suffix |

Other examples: finir, choisir, guérir, applaudir, rallentir, rougir

## Terzo gruppo (-ir, -oir, -re)

### -re

Écrire, lire, mettre, répondre. On the plural, we add/change a consonant. Different consonant for different verbs.

|      | Lire       | Mettre      | Écrire       | Répondre       |
|------|------------|-------------|--------------|----------------|
| Je   | li**s**    | met**s**    | écris | réponds |
| Tu   | li**s**    | met**s**    | écris | réponds |
| Il   | li**t**    | me**t**     | écrit | répond |
| Nous | lis**ons** | mett**ons** | écrivon | répondons |
| Vous | lis**ez**  | mett**ez**  | écrivez | répondez |
| Ils  | lis**ent** | mett**ent** | écrivent | répondent |

**Note**: lad -d in répon**d**re é muta per le persone al singolare, sonora per quelle al plurale.

- Come Lire: interdire, plaire, verbs en "uire": construire, conduire
- Come Écrire: décrire, inscrire
- Come Mettre: battre, permettre, promettre
- Come Répondre: entendre, attendre, vendre, perdre

|      | Faire       | Dire       | boire      | prendre      | Connaître       | Croire      |
|------|--------     |--------    |--------    |--------      |--------         |--------     |
| Je   | fai**s**    | di**s**    | boi**s**   | prend**s**   | connai**s**     | croi**s**   |
| Tu   | fai**s**    | di**s**    | boi**s**   | prend**s**   | connai**s**     | croi**s**   |
| Il   | fai**t**    | di**t**    | boi**t**   | prend        | connaî**t**     | croi**t**   |
| Nous | fais**ons** | dis**ons** | buv**ons** | pren**ons**  | connaiss**ons** | croy**ons** |
| Vous | faites      | dites      | buv**ez**  | pren**ez**   | connaiss**ez**  | croy**ez**  |
| Ils  | font        | dis**ent** | buv**ent** | prenn**ent** | connaiss**ent** | croi**ent** |

- Come prendre: apprendre, comprendre

### -ir

Examples: partir, dormir, sortir

|      | dormir      | partir  | servir  | venir    |
|------|-------------| ---     | ---     | --       |
| Je   | dor**s**    | pars    | sers    | viens    |
| Tu   | dor**s**    | pars    | sers    | viens    |
| Il   | dor**t**    | part    | sert    | vient    |
| Nous | dorm**ons** | parton  | servons | venons   |
| Vous | dorm**ez**  | partez  | servez  | venez    |
| Ils  | dorm**ent** | partent | servent | viennent |

- Come venir: reveneir, devenir, tenir, se souvenir

### -oir

|      | Vouloir | Pouvoir | Devoir  | Recevoir  | Savoir | Voir   |
|------|---------|---------|---------|-----------|--------|--------|
| Je   | veux    | peux    | dois    | reçois    | sais   | vois   |
| Tu   | veux    | peux    | dois    | reçois    | sais   | vois   |
| Il   | veut    | peut    | doit    | reçoit    | sait   | voit   |
| Nous | voulons | pouvons | devons  | recevons  | savon  | voyons |
| Vous | voulez  | pouvez  | devez   | recevez   | savez  | voyez  |
| Ils  | veulent | peuvent | doivent | reçoivent | savent | voient |



